#!/usr/bin/env python3
"""
调试脚本：对比录制和replay的详细执行流程
帮助找出导致replay失效的根本原因
"""

print("=" * 80)
print("录制 vs Replay 调试指南")
print("=" * 80)
print()

print("基于详细分析，最可能的问题是：")
print()
print("1. Observation计算的差异")
print("2. History buffer的初始化差异")
print("3. Decimation循环中的细微差异")
print()

print("=" * 80)
print("调试步骤1：添加详细日志到录制脚本")
print("=" * 80)
print()

print("在 action_provider_wh_twist2.py 的 get_action() 函数中添加：")
print()
print("```python")
print("# 在 line 1392 (run_policy之前) 添加：")
print("if self.sim_step_counter <= 2:")
print("    print(f'\\n=== Recording Frame {self.sim_step_counter} START ===')")
print("    print(f'  _obs_counter: {self._obs_counter}')")
print("    print(f'  _obs_interval: {self._obs_interval}')")
print("    print(f'  joint_pos (first 5): {self.joint_pos[0, self.twist2_action_indices[:5]]}')")
print("    print(f'  joint_vel (first 5): {self.joint_vel[0, self.twist2_action_indices[:5]]}')")
print()
print("# 在 line 1393 (run_policy之后) 添加：")
print("if self.sim_step_counter <= 2:")
print("    print(f'  obs_buf (first 10): {obs_buf[0, :10]}')")
print("    print(f'  action_data (first 5): {action_data[0, :5]}')")
print("    print(f'  target_29 (first 5): {target_29[0, :5]}')")
print()
print("# 在 line 1587 (decimation循环之后) 添加：")
print("if self.sim_step_counter <= 2:")
print("    print(f'  After decimation:')")
print("    print(f'    joint_pos (first 5): {self.env.scene[\"robot\"].data.joint_pos[0, self.twist2_action_indices[:5]]}')")
print("    print(f'    joint_vel (first 5): {self.env.scene[\"robot\"].data.joint_vel[0, self.twist2_action_indices[:5]]}')")
print("    print(f'=== Recording Frame {self.sim_step_counter} END ===\\n')")
print("```")
print()

print("=" * 80)
print("调试步骤2：添加详细日志到replay脚本")
print("=" * 80)
print()

print("在 action_provider_wh_twist2_replay.py 的 get_action() 函数中添加：")
print()
print("```python")
print("# 在 line 595 (inference mode开始) 添加：")
print("if self.current_frame <= 2:")
print("    print(f'\\n=== Replay Frame {self.current_frame} START ===')")
print("    robot = self.env.scene[\"robot\"]")
print("    print(f'  Before action:')")
print("    print(f'    joint_pos (first 5): {robot.data.joint_pos[0, self.twist2_action_indices[:5]]}')")
print("    print(f'    joint_vel (first 5): {robot.data.joint_vel[0, self.twist2_action_indices[:5]]}')")
print()
print("# 在 line 606 (ONNX推理之后，inference mode) 添加：")
print("if self.current_frame <= 2:")
print("    print(f'  obs_tensor (first 10): {obs_tensor[0, :10]}')")
print("    print(f'  action_data (first 5): {action_data[0, :5]}')")
print("    print(f'  target_29 (first 5): {target_29[0, :5]}')")
print()
print("# 在 line 622 (direct mode) 添加：")
print("if self.current_frame <= 2:")
print("    print(f'  Direct mode: target_29 (first 5): {target_29[0, :5]}')")
print()
print("# 在 line 671 (decimation循环之后) 添加：")
print("if self.current_frame <= 2:")
print("    print(f'  After decimation:')")
print("    print(f'    joint_pos (first 5): {robot.data.joint_pos[0, self.twist2_action_indices[:5]]}')")
print("    print(f'    joint_vel (first 5): {robot.data.joint_vel[0, self.twist2_action_indices[:5]]}')")
print("    print(f'=== Replay Frame {self.current_frame} END ===\\n')")
print("```")
print()

print("=" * 80)
print("调试步骤3：运行并对比输出")
print("=" * 80)
print()

print("1. 重新录制数据（从reset开始）：")
print("   bash run.sh")
print("   (录制前3帧，然后停止)")
print()

print("2. 运行replay（direct模式）：")
print("   ./run_replay.sh <recording_file> direct")
print("   (replay前3帧)")
print()

print("3. 对比输出：")
print("   - Frame 0 START 的 joint_pos 和 joint_vel 应该完全相同")
print("   - target_29 应该完全相同（direct模式）")
print("   - Frame 0 END 的 joint_pos 和 joint_vel 应该完全相同")
print("   - 如果不同，找出第一个不同的地方")
print()

print("=" * 80)
print("调试步骤4：检查decimation循环内部")
print("=" * 80)
print()

print("如果Frame 0 END的状态不同，需要检查decimation循环内部：")
print()
print("在两个脚本的decimation循环中添加（只在Frame 0时）：")
print()
print("```python")
print("for i in range(self._twist2_decimation):  # 或 decimation")
print("    if self.sim_step_counter == 0:  # 或 self.current_frame == 0")
print("        qpos_before = self.env.scene['robot'].data.joint_pos[0, self.twist2_action_indices[:5]].clone()")
print("        qvel_before = self.env.scene['robot'].data.joint_vel[0, self.twist2_action_indices[:5]].clone()")
print()
print("    self.env.scene['robot'].set_joint_position_target(full_action)")
print("    self.env.scene.write_data_to_sim()")
print("    self.env.sim.step(render=False)")
print("    self.env.scene.update(dt=self.env.physics_dt)")
print()
print("    if self.sim_step_counter == 0:  # 或 self.current_frame == 0")
print("        qpos_after = self.env.scene['robot'].data.joint_pos[0, self.twist2_action_indices[:5]]")
print("        qvel_after = self.env.scene['robot'].data.joint_vel[0, self.twist2_action_indices[:5]]")
print("        print(f'  Decimation step {i}:')")
print("        print(f'    qpos change: {qpos_after - qpos_before}')")
print("        print(f'    qvel change: {qvel_after - qvel_before}')")
print("```")
print()

print("=" * 80)
print("预期结果")
print("=" * 80)
print()

print("如果一切正确，应该看到：")
print()
print("Recording Frame 0:")
print("  joint_pos: [0.0792, -0.1144, 0.0221, 0.0413, -0.0567]")
print("  target_29: [0.0202, 0.1264, -0.0772, -0.0571, 0.0058]")
print("  After decimation:")
print("    joint_pos: [0.1365, -0.0831, 0.0557, -0.0249, -0.0506]")
print()
print("Replay Frame 0 (direct mode):")
print("  joint_pos: [0.0792, -0.1144, 0.0221, 0.0413, -0.0567]  ← 应该相同")
print("  target_29: [0.0202, 0.1264, -0.0772, -0.0571, 0.0058]  ← 应该相同")
print("  After decimation:")
print("    joint_pos: [0.1365, -0.0831, 0.0557, -0.0249, -0.0506]  ← 应该相同")
print()
print("如果不同，找出第一个不同的地方，那就是问题所在！")
print()

print("=" * 80)
print("可能的问题点")
print("=" * 80)
print()

print("1. 如果 target_29 不同：")
print("   - 检查 twist2_default_pos 是否相同")
print("   - 检查 action scaling (0.5) 是否应用")
print("   - 检查 clip 操作是否应用")
print()

print("2. 如果 decimation 后的状态不同：")
print("   - 检查 PD 参数（Kp, Kd）")
print("   - 检查 physics dt")
print("   - 检查 solver iterations")
print("   - 检查 decimation 次数")
print()

print("3. 如果某个 decimation step 的变化不同：")
print("   - 那一步的 physics 计算有差异")
print("   - 可能是接触力、约束求解等")
print()

print("=" * 80)
print("总结")
print("=" * 80)
print()

print("通过这个详细的调试流程，你应该能够：")
print("1. 精确定位第一个产生差异的位置")
print("2. 理解差异的原因")
print("3. 找到修复方法")
print()

print("如果所有输入都相同但输出仍然不同，那就是物理引擎的非确定性，")
print("需要考虑使用混合模式（定期状态重置）。")
print()

print("祝调试顺利！")
