#!/usr/bin/env python3
"""验证初始状态设置的正确性"""

import numpy as np

# 加载录制数据
data = np.load('recording_data/Isaac-Move-Football-G129-Dex3-Wholebody_1773326197574686.npz')

print('='*80)
print('初始状态设置验证')
print('='*80)

print('\n问题: 为什么 Frame 1 的 joint velocity error 是 0.74 rad/s？')
print()

print('假设 1: Frame 0 初始状态设置不正确')
print('-'*80)
print('如果 Frame 0 的关节速度没有正确设置:')
print(f'  期望的 Frame 0 joint velocity L2: {np.linalg.norm(data["robot_qvel_before_decimation"][0]):.4f} rad/s')
print(f'  如果设置为 0: 误差 = {np.linalg.norm(data["robot_qvel_before_decimation"][0]):.4f} rad/s')
print()
print('应用 action[0] 后:')
print(f'  期望的 Frame 1 joint velocity L2: {np.linalg.norm(data["robot_qvel_before_decimation"][1]):.4f} rad/s')
print(f'  如果从 0 开始: 可能产生较大误差')
print()
print('但是代码中明确设置了 joint velocity (line 377-391)')
print('所以这个假设可能不成立')

print('\n假设 2: write_joint_state_to_sim 没有立即生效')
print('-'*80)
print('如果 write_joint_state_to_sim 只是写入 buffer:')
print('  → 需要调用 write_data_to_sim() 才能写入物理引擎')
print('  → 或者需要等到第一次 sim.step()')
print()
print('当前代码流程:')
print('  1. set_initial_state_before_simulation():')
print('     - write_root_state_to_sim()')
print('     - write_joint_state_to_sim()')
print('     - 注释说: DO NOT call write_data_to_sim()')
print('  2. 第一次 get_action() (current_frame == 0):')
print('     - 应用 Frame 0 action')
print('     - 运行 decimation loop:')
print('       - set_joint_position_target()')
print('       - write_data_to_sim()  ← 这里才写入物理引擎！')
print('       - sim.step()')
print()
print('问题: 在第一次 write_data_to_sim() 时:')
print('  - 初始状态 (位置、速度) 是否已经在物理引擎中？')
print('  - 还是在这一刻才写入？')
print('  - 如果是后者，那么初始速度可能被覆盖或丢失！')

print('\n假设 3: PD 控制器在第一个 decimation step 就开始作用')
print('-'*80)
print('如果在第一个 decimation step:')
print('  1. write_data_to_sim() 同时写入:')
print('     - 初始状态 (位置、速度)')
print('     - PD 目标 (Frame 0 action)')
print('  2. sim.step() 计算:')
print('     - PD 控制器看到当前速度和目标位置')
print('     - 产生力矩')
print('     - 更新速度')
print()
print('这可能导致:')
print('  - 初始速度被 PD 控制器立即修改')
print('  - 产生与录制不同的速度变化')

print('\n验证方法:')
print('-'*80)
print('1. 在 set_initial_state_before_simulation() 后立即读取状态')
print('   - 检查关节速度是否正确设置')
print('2. 在第一次 decimation loop 的第一个 step 前读取状态')
print('   - 检查速度是否还保持')
print('3. 在第一次 decimation loop 的第一个 step 后读取状态')
print('   - 检查速度如何变化')

print('\n建议的修复:')
print('-'*80)
print('方案 A: 在设置初始状态后立即调用 write_data_to_sim()')
print('  - 确保初始状态立即写入物理引擎')
print('  - 然后再应用 Frame 0 action')
print()
print('方案 B: 在第一次 decimation loop 前，先运行一次 sim.step()')
print('  - 让初始状态在物理引擎中稳定')
print('  - 然后再应用 Frame 0 action')
print()
print('方案 C: 修改 decimation loop，第一个 step 不应用 PD 控制')
print('  - 只让初始状态在物理引擎中生效')
print('  - 从第二个 step 开始应用 PD 控制')
print('='*80)
