#!/bin/bash
# SONIC修复后的完整测试检查清单

echo "========================================================================"
echo "SONIC修复验证 - 完整检查清单"
echo "========================================================================"
echo ""
echo "已修复的Bug："
echo "  1. Encoder输入字段全0 → 用实际机器人状态填充"
echo "  2. 历史缓冲区太短(10帧) → 扩大到46帧"
echo ""
echo "========================================================================"
echo "步骤1：离线验证（无需VR）"
echo "========================================================================"
echo ""
echo "运行以下命令验证修复："
echo ""
echo "  cd /home/dreams/Users/taowen/HumanoidArena/isaaclab_twist2_g1/tools"
echo "  python verify_fix.py"
echo "  python verify_history_fix.py"
echo ""
echo "预期结果："
echo "  ✅ Latent变化 > 0.01"
echo "  ✅ 历史缓冲区采样成功"
echo ""
echo "========================================================================"
echo "步骤2：启动系统"
echo "========================================================================"
echo ""
echo "终端1 - 启动pico_server："
echo "  cd /home/dreams/Users/Alyssa/HumanoidArena_V1/GR00T-WholeBodyControl/gear_sonic"
echo "  python pico_manager_thread_server.py"
echo ""
echo "终端2 - 启动IsaacLab："
echo "  cd /home/dreams/Users/taowen/HumanoidArena/isaaclab_twist2_g1"
echo "  ./run.sh"
echo ""
echo "========================================================================"
echo "步骤3：VR测试"
echo "========================================================================"
echo ""
echo "1. 戴上Pico头显，确保追踪正常"
echo "2. 规律地左右甩手（频率约1Hz，持续5秒）"
echo "3. 观察IsaacLab仿真窗口"
echo ""
echo "========================================================================"
echo "步骤4：检查日志"
echo "========================================================================"
echo ""
echo "在IsaacLab终端中查找以下关键日志："
echo ""
echo "1. 历史缓冲区已满："
echo "   [SONIC][HISTORY] smpl_history_fill=10/10 smpl_valid=True"
echo ""
echo "2. Encoder输入非零："
echo "   [SONIC][ENCODER_INPUT] motion_pos_step5=[-0.2000, 0.4000]"
echo "   （不应该是[0.0000, 0.0000]）"
echo ""
echo "3. Latent正常变化："
echo "   [DEBUG_LATENT] Latent最大变化: 0.XXXXXX"
echo "   （应该 > 0.01，不是0.000000）"
echo ""
echo "4. Action正常变化："
echo "   [DEBUG_ACTION] Action最大变化: 0.XXXXXX"
echo "   （应该 > 0.01）"
echo ""
echo "5. 最终输出不是默认值："
echo "   [SONIC_29_QPOS_VALUES] [...]"
echo "   （不应该全是 -0.2, -0.2, 0, 0, 0, 0.4, 0.4, ...）"
echo ""
echo "========================================================================"
echo "预期结果"
echo "========================================================================"
echo ""
echo "✅ 修复成功的标志："
echo "   - 机器人手臂跟随VR规律摆动"
echo "   - 左右甩手时，仿真中也左右摆动"
echo "   - 有明显的规律性（约1Hz）"
echo "   - Latent和Action都有规律变化"
echo ""
echo "❌ 如果仍有问题："
echo "   - 检查SMPL数据是否接收（运行 tools/monitor_sonic_live.py）"
echo "   - 检查encoder/decoder模型是否加载成功"
echo "   - 查看完整日志，寻找错误信息"
echo ""
echo "========================================================================"
echo "故障排查"
echo "========================================================================"
echo ""
echo "问题1：仍然输出默认值"
echo "  → 检查 [DEBUG_LATENT] 是否变化"
echo "  → 如果不变，检查 [SONIC][ENCODER_INPUT] 是否非零"
echo ""
echo "问题2：报错 'History too short'"
echo "  → 确认已重启IsaacLab（修改后需要重启）"
echo "  → 检查代码是否正确修改（第505-510行）"
echo ""
echo "问题3：机器人动作不规律"
echo "  → 检查VR追踪是否稳定"
echo "  → 检查ZMQ连接是否正常"
echo "  → 运行 tools/detect_periodic_motion.py 分析周期性"
echo ""
echo "========================================================================"
