#!/bin/bash
# SONIC修复后的快速测试指南

echo "=========================================="
echo "SONIC Latent不变问题 - 修复验证"
echo "=========================================="
echo ""
echo "问题：VR中规律甩手，仿真不跟随"
echo "根因：encoder输入的机器人状态字段全是0"
echo "修复：用实际机器人状态填充encoder输入"
echo ""
echo "=========================================="
echo "测试步骤"
echo "=========================================="
echo ""
echo "1. 启动pico_server（gear_sonic侧）"
echo "   cd /home/dreams/Users/Alyssa/HumanoidArena_V1/GR00T-WholeBodyControl/gear_sonic"
echo "   python pico_manager_thread_server.py"
echo ""
echo "2. 启动IsaacLab仿真（新终端）"
echo "   cd /home/dreams/Users/taowen/HumanoidArena/isaaclab_twist2_g1"
echo "   ./run.sh"
echo ""
echo "3. 在VR中测试"
echo "   - 戴上Pico头显"
echo "   - 规律地左右甩手（频率约1Hz）"
echo "   - 持续5秒"
echo ""
echo "4. 观察仿真"
echo "   - 机器人手臂是否跟随VR运动"
echo "   - 是否有明显的规律性（左右摆动）"
echo "   - 延迟是否在可接受范围（<200ms）"
echo ""
echo "=========================================="
echo "预期结果"
echo "=========================================="
echo ""
echo "✅ 修复前："
echo "   - 机器人有动作但不规律"
echo "   - 不跟随VR运动"
echo "   - Latent输出不变"
echo ""
echo "✅ 修复后："
echo "   - 机器人手臂跟随VR规律摆动"
echo "   - 左右甩手时，仿真中也左右摆动"
echo "   - Latent输出随SMPL变化"
echo ""
echo "=========================================="
echo "调试日志关键字"
echo "=========================================="
echo ""
echo "查看这些日志确认修复生效："
echo ""
echo "[DEBUG_LATENT] Latent最大变化: 0.XXXXXX"
echo "  - 修复前：0.000000（不变）"
echo "  - 修复后：>0.01（正常变化）"
echo ""
echo "[SONIC][ENCODER_INPUT] motion_pos_step5=[...]"
echo "  - 修复前：全是0或接近0"
echo "  - 修复后：有合理的关节角度值（-0.2到0.4范围）"
echo ""
echo "=========================================="
echo "如果仍有问题"
echo "=========================================="
echo ""
echo "1. 检查ZMQ连接"
echo "   python tools/monitor_sonic_live.py"
echo "   确认SMPL数据正常接收"
echo ""
echo "2. 检查encoder输入"
echo "   查看日志中的 [DEBUG_ENC_DETAIL]"
echo "   确认encoder输入不是全0"
echo ""
echo "3. 检查latent变化"
echo "   查看日志中的 [DEBUG_LATENT]"
echo "   确认latent随SMPL变化"
echo ""
echo "4. 运行离线验证"
echo "   python tools/verify_fix.py"
echo "   确认修复逻辑正确"
echo ""
